//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ingreso_de_Vehiculos.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Colegio
    {
        public int Id_Colegio { get; set; }
        public string nombre_colegio { get; set; }
        public string descripcion { get; set; }
        public string url_imagen { get; set; }
    }
}
