//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ingreso_de_Vehiculos.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DB_A1E868_ingresoCTPEntities : DbContext
    {
        public DB_A1E868_ingresoCTPEntities()
            : base("name=DB_A1E868_ingresoCTPEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Colegio> Colegio { get; set; }
        public virtual DbSet<departamentos> departamentos { get; set; }
        public virtual DbSet<Visitantes> Visitantes { get; set; }
        public virtual DbSet<TSE> TSE { get; set; }
    }
}
