//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ingreso_de_Vehiculos.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Visitantes
    {
        public int id_visitante { get; set; }
        public string cedula { get; set; }
        public string nombre { get; set; }
        public string apellidos { get; set; }
        public Nullable<System.DateTime> fecha_nacimiento { get; set; }
        public Nullable<System.DateTime> fecha_ingreso { get; set; }
        public string placa { get; set; }
        public Nullable<int> id_departamento { get; set; }
    
        public virtual departamentos departamentos { get; set; }
    }
}
